openapi: 3.0.3
info:
  title: Sample API
  description: API for managing items
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /items:
    get:
      summary: Retrieve a list of items
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'

    post:
      summary: Create a new item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewItem'
      responses:
        '201':
          description: Item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'

  /items/{id}:
    get:
      summary: Retrieve a specific item by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Item not found

components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: string
          example: '123'
        name:
          type: string
          example: 'Sample Item'
        description:
          type: string
          example: 'This is a sample item.'

    NewItem:
      type: object
      properties:
        name:
          type: string
          example: 'New Item'
        description:
          type: string
          example: 'This is a new item.'
